name: Mark Tasks Overdue
on:
  workflow_dispatch
jobs:
  Ubuntu:
    name: Add labels to overdue issues
    runs-on: ubuntu-latest
    steps:
      - name: GitHub Issue Due Dates Action
        uses: Recidiviz/github-issue-due-dates-action@v2.7
        with:
          GH_TOKEN: "${{ secrets.GH_TOKEN }}"
